name: databag

services:
  app:
    build: .

    # # For building cross environment containers
    # build:
    #   context: .
    #   args:
    #     DATABAG_GOARCH: arm64
    #     DATABAG_GOOS: linux
    # platform: "linux/arm64"
    ports:
      - 0.0.0.0:7000:7000
    volumes:
      - database:/var/lib/databag
      - ./token_data:/var/lib/token_data
    environment:
      - ADMIN=password

volumes:
  database:
